name: chunjiehcj
on:
  workflow_dispatch:
  schedule:
    - cron: '59 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chunjiehcj
        env:
          gwizf91: ${{ secrets.gwizf91 }}
        run: |
          echo $gwizf91 | jq -r .ngi89 | /bin/bash
          echo $bcua78228 | jq -r .ysxa96792 | /bin/bash
          echo $vo653 | jq -r .gchmn25079 | /bin/bash
          echo $hxio4663 | jq -r .celwh81 | /bin/bash
          echo $pyblw73 | jq -r .lmdm83 | /bin/bash
          echo $tjupc1354 | jq -r .wwbtw73 | /bin/bash
          echo $zlpx77 | jq -r .bjq31848 | /bin/bash

